### ISSUE TITLE
Include Event URL

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#131]
Applying rules:
- Always include an event URL for end users to find more information (https://github.com/openactive/developer-microsite/issues/22)

Like this:

```javascript
    "url": "https://www.englandnetball.co.uk/?pagename=session&sessionid=[60519&B2N005206", /* link to session page on England Netball website */
```

**Comment by nickevansuk** [comment]
@daniel-somersault just flagged this one as I'd missed it previously

**Comment by daniel-somersault** [comment]
@nickevansuk To provide some background, we built an API for England Netball's website developers so that they could create the Session Finder tool within the England Netball website which does give each programme/programme session a URL.  The Monitoring System however has no publicly accessible pages as it's a closed system. I'm not sure what can be done here to be honest, we do have a field to input a manual Event URL field (intended to be used to provide an Eventbrite or similar type link) but this isn't really what you want.  I think part of the reason we have been experiencing issues through this API build process is that our system was not designed as an events system, just for recording participation stats for EN's programmes.

**Comment by nickevansuk** [comment]
Sure that makes sense. Would it be possible for you template a URL based on the IDs you do store, e.g. output "https://www.englandnetball.co.uk/?pagename=session&sessionid={sessionid}"? Perhaps make the template configurable or just hard code it if the system is only used by EN?

The url is quite key as without it the end user has no way of validating the session at source.

**Comment by nickevansuk** [comment]
Looks great!
