### ISSUE TITLE
Assumption: modified date

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#40]
Checking the assumption that the item modified date will be updated if the channel data is updated

**Comment by ElliottJPerry** [comment]
Re-reading it I can see this covered in 4.4 Related entities of the specification, my bad. This is currently not the case. Due to internal reasons this is not as trivial as updating the events relating to a channel once that channel is updated. Would the omission of this prevent us from pushing on to see some adoption in the meantime?

**Comment by nickevansuk** [comment]
Something for data users be aware of as updates to channels will not affect existing sessions until they are updated, which could cause confusion for end users. As the time-critical data is in the session, I've gone ahead and published this dataset to Openactive on the basis that you'll work on resolving this as your adoption increases.

It's best to make a note of this issue in your documentation so that data consumers are aware, and raise it as an outstanding issue on your documentation GitHub repo. When you make the fix, simply notify any users of your data via the mailing list and close your GitHub issue.

**Comment by ElliottJPerry** [comment]
Technically version v0.2.3, as mentioned at the top of the documentation repo, makes no mention of this requirement ;)

But agreed...
Updated docs: https://github.com/flex-tv/opendata
Issue: https://github.com/flex-tv/opendata/issues/1

**Comment by nickevansuk** [comment]
Great spot on the technicality, the next spec v0.3 will be water-tight with you on-board  😛
